language: cpp
compiler:
  - clang
  - gcc
before_script:
    - sudo apt-get -qq update
    - sudo apt-get -qq install gcc
    - sudo apt-get -qq install valgrind
script: make test
os:
    - linux
    - osx
